In [60]:
data = np.loadtxt('data.csv', delimiter = ',')

In [78]:
np.shape(data)

(100, 2)

In [81]:
np.shape(data[:,-1])

(100,)

In [80]:
np.shape(data[:,:-1])

(100, 1)

In [105]:
X = data[:,:-1]
y = data[:,-1]

n_points = X.shape[0]
W = np.zeros(X.shape[1])
b=0

regression_coef = [np.hstack((W,b))]

In [97]:
np.random.choice(range(n_points), 25)

array([96, 19, 28, 89, 99, 88, 39, 47, 57, 80, 95, 65, 40, 10, 14,  7,  8,
       31, 51, 88, 61, 51, 83, 94, 30])

In [98]:
batch = np.random.choice(range(n_points), 25)
X[batch,:]

array([[ 0.79862],
       [-0.9829 ],
       [-0.75463],
       [ 0.89583],
       [ 0.32924],
       [ 0.24625],
       [ 0.4552 ],
       [-1.36115],
       [-0.95409],
       [ 0.49594],
       [-0.44442],
       [ 0.62822],
       [ 0.67312],
       [-1.34999],
       [ 2.64837],
       [ 1.30499],
       [ 0.10883],
       [ 0.74678],
       [ 0.15835],
       [ 0.01763],
       [-2.40724],
       [-0.60116],
       [-0.00604],
       [-3.02296],
       [ 0.03283]])

In [99]:
y[batch]

array([ 3.44953e+00,  2.30455e+00,  2.30161e+00,  3.04041e+00,
        1.91416e+00,  2.33029e+00,  2.31938e+00,  1.70969e+00,
        1.86155e+00,  1.96178e+00,  2.06623e+00,  1.71526e+00,
        2.05950e+00,  1.59958e+00,  3.01665e+00,  2.42824e+00,
        6.31900e-01,  2.92253e+00,  2.28231e+00,  1.87838e+00,
       -1.56000e-03,  1.54254e+00,  1.78802e+00,  1.09255e+00,
        1.55730e+00])

In [100]:
X_batch = X[batch,:]
y_batch = y[batch]

In [101]:
W, b = 0,0 #MSEStep(X_batch, y_batch, W, b, learn_rate)

regression_coef.append(np.hstack((W,b)))

In [102]:
regression_coef

[array([0., 0.]), array([0, 0])]

In [106]:
W

array([0.])

In [109]:
np.matmul(X,W)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])